### ISSUE TITLE
Finish refactoring and unit testing of PointCloud

### ISSUE THREAD

**Issue by Martin-Idel-SI** [ros2/rviz#126]
PointCloud has now been ported, however, we didn't get to do everything we want. Here is what would be necessary or nice to have but which is currently not possible:

- [x] Introduce pluginlib (requires https://github.com/ros2/rviz/issues/49, already on branch)
- [x] Introduce pluginlib to transformers
- [x] Add tests to PointCloudCommon (requires https://github.com/ros2/rviz/issues/125) + refactoring of `update`
- [x] Add tests to PointCloudSelectionHandler + refactoring (requires a SelectionManager and therefore https://github.com/ros2/rviz/issues/125)
- [x] Reintroduce RosTopicProperty in MessageFilterDisplay to see available topics (was replaced by StringProperty)
- [x] ~~Reintroduce/find alternative to tf2 message filter (not ported, yet)~~ tracked by #55
- [x] Hide/Show only transformer properties that should be visible (see comment below)
- [x] Migrate or delete old point cloud tests (make sure functionality is tested)

**Comment by greimela-si** [comment]
I extracted the pluginlib integration into a separate issue (#135).

**Comment by Martin-Idel-SI** [comment]
Using the IntensityPCTransformer, the default visibility of some properties is not correct although it seems to be correctly set (autocompute intensity property is checked, but the manual min and max values are still visible, a similar problem is seen with the rainbow property). 

This could be investigated when introducing pluginlib to transformers.
